### PR TITLE
Performance improvment

### PR DESCRIPTION
**Pull request by 200MPH**
The program works fine on short date range and fewer data.
However takes ages when processing lot of records contains long date range.
It was caused buy too many nested loops.
I've changed it so it's lookup to array keys instead looping through which speed it up significant.
Based on data I was working on I have reduced processing time from 19 seconds to 1 second.

### CODE REVIEW

**Comment by 200MPH** [comment]
Will have a look to Travis but what's wrong Style CI?

**Comment by Jord-JD** [comment]
Regarding StyleCI, just download the diff and use `git apply` to make the changes.

**Comment by 200MPH** [comment]
@DivineOmega I did and got this errors

warning: src/Factories/UkBankHolidayFactory.php has type 100644, expected 100755
error: patch failed: src/Factories/UkBankHolidayFactory.php:15
error: src/Factories/UkBankHolidayFactory.php: patch does not apply

Sorry I'm not familiar with this tool please advise.

**Pull request closed without merging**
