### PR TITLE
Update DOFileCacheDriver.php

### PR DESCRIPTION
**Pull request by 200MPH**
Save cache did not work without this extra line.
After adding it it's caching as expected :)

### CODE REVIEW

**Comment by Jord-JD** [comment]
This looks great, thanks.

Could you fix the issues reported by Style CI and remove HHVM support from the Travis file?

**Comment by 200MPH** [comment]
Sure, I will do

**Comment by 200MPH** [comment]
All looks good :)

**Comment by Jord-JD** [comment]
Thanks! Released as [v5.0.0](https://github.com/rapidwebltd/php-uk-bank-holidays/releases/tag/v5.0.0).

**Pull request merged**
